name: my_first_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
# homepage: https://www.example.com

environment:
  sdk: '>=3.10.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  email_validator: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
